/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import DB_pokemon.ConexionDB;
import DB_pokemon.Mysql_pokemon;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Ruldin
 */
public class VentanaPokedex extends javax.swing.JFrame {
    private final Mysql_pokemon pokemon = new Mysql_pokemon();
    BufferedImage buffer1 =null;

    Image imagen1 = null;
 
    int contador_bd = 1;
    int contador_poke=0;
    
    Statement estado;
    ResultSet resultadoConsulta;
    Connection conexion;
    
    @Override
    public void paint(Graphics g){
        super.paintComponents(g);
        Graphics2D g2 =(Graphics2D) imagenPokemon.getGraphics();
        
        g2.drawImage(buffer1, 0,0,imagenPokemon.getWidth(),imagenPokemon.getHeight(),null);
    }
    
    
    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {
        
        initComponents();
        init_componentes();
        setTitle("Pokedex");
        setLocationRelativeTo(null); //mostrar ventana en el centro
       
        pokemon.consulta_nombtepk(this.pokemon.consulta_pokemon(""+contador_bd));
        pokemon.desplegar_datospk(nombre, alto, ancho, especies, color, habitat, experiencia);

    }
    private void init_componentes(){
        obtener_imagen("C:\\Users\\USUARIOTC\\Downloads\\Telegram Desktop\\datos\\imagenes\\black-white.png");
        dibujaElPokemonQueEstaEnLaPosicion(contador_poke);
        nombrePokemon.setText(this.pokemon.consulta_pokemon(""+contador_bd)); 
        
    }

    private void obtener_imagen(String directorio){
        try {
            //imagen1 = ImageIO.read(getClass().getResource("/imagenes/back-white.png"));
            imagen1 =ImageIO.read(new File(directorio));
        } catch (IOException ex) {
            ex.printStackTrace(System.out);
        }
        
        buffer1 = (BufferedImage) imagenPokemon.createImage(
                imagenPokemon.getWidth(),
                imagenPokemon.getHeight());
        
        Graphics2D g2 = buffer1.createGraphics();
        
    }
    //Dibuja el pokemon
    private void dibujaElPokemonQueEstaEnLaPosicion(int posicion){
        int fila = posicion / 31;
        int columna = posicion % 31;
        
        Graphics2D g2 = (Graphics2D) buffer1.getGraphics();
        g2.setColor(Color.black);
        
        g2.fillRect(0, 0, //pinta el fondo del jpanel negro
                imagenPokemon.getWidth(),
                imagenPokemon.getHeight()); 
        
        
        g2.drawImage(imagen1,
                0,  //posicion X inicial dentro del jpanel 
                0,  // posicion Y inicial dentro del jpanel
                imagenPokemon.getWidth(), //ancho del jpanel
                imagenPokemon.getHeight(), //alto del jpanel
                columna*96, //posicion inicial X dentro de la imagen de todos los pokemon
                fila*96, //posicion inicial Y dentro de la imagen de todos los pokemon
                columna*96 + 96, //posicion final X
                fila*96 + 96, //posicion final Y
                null  //si no lo pones no va
                );
        
        repaint();   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        izq = new javax.swing.JButton();
        der = new javax.swing.JButton();
        imagenPokemon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreusuario = new javax.swing.JTextField();
        nombrePokemon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        alto = new javax.swing.JLabel();
        ancho = new javax.swing.JLabel();
        especies = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        habitat = new javax.swing.JLabel();
        experiencia = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AgregarFav = new javax.swing.JButton();
        AgregarmenosFav = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BFavoritos = new javax.swing.JButton();
        BGenerarPdf = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        izq.setIcon(new javax.swing.ImageIcon("C:\\Users\\13237\\OneDrive\\Desktop\\pokedexp1A\\pokedexp1A\\src\\main\\java\\imagenes\\flechaizquierda.png")); // NOI18N
        izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izqActionPerformed(evt);
            }
        });
        getContentPane().add(izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 70, 60));

        der.setIcon(new javax.swing.ImageIcon("C:\\Users\\13237\\OneDrive\\Desktop\\pokedexp1A\\pokedexp1A\\src\\main\\java\\imagenes\\flechaderecha.png")); // NOI18N
        der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derActionPerformed(evt);
            }
        });
        getContentPane().add(der, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 70, 60));

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagenPokemonLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(198, 198, 198))
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenPokemonLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(imagenPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 220, 180));

        nombreusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 180, 30));

        nombrePokemon.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        nombrePokemon.setText("nombre");
        getContentPane().add(nombrePokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 362, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Bienvenido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Especie:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Alto:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Ancho:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Experiencia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Color:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Habitad:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        alto.setBackground(new java.awt.Color(153, 51, 255));
        alto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alto.setText("jLabel1");
        alto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 2, true));
        alto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(alto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, 20));

        ancho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ancho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ancho.setText("jLabel1");
        ancho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 204), 2, true));
        getContentPane().add(ancho, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 60, 20));

        especies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        especies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        especies.setText("jLabel1");
        especies.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 204), 2, true));
        getContentPane().add(especies, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 60, 20));

        color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        color.setText("jLabel1");
        color.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 231, 31), 2, true));
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 60, 20));

        habitat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        habitat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        habitat.setText("jLabel1");
        habitat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 114, 187), 2, true));
        getContentPane().add(habitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 60, 20));

        experiencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        experiencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        experiencia.setText("jLabel1");
        experiencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 226), 2, true));
        getContentPane().add(experiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 60, 20));

        nombre.setIcon(new javax.swing.ImageIcon("C:\\Users\\13237\\OneDrive\\Desktop\\imagenesfinalprogra\\fondopokemon.PNG")); // NOI18N
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Agregar a Favoritos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        AgregarFav.setIcon(new javax.swing.ImageIcon("C:\\Users\\13237\\OneDrive\\Desktop\\imagenesfinalprogra\\y.png")); // NOI18N
        AgregarFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFavActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 60, 50));

        AgregarmenosFav.setIcon(new javax.swing.ImageIcon("C:\\Users\\13237\\OneDrive\\Desktop\\imagenesfinalprogra\\x.png")); // NOI18N
        AgregarmenosFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarmenosFavActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarmenosFav, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 60, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Agregar a menos Fav.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        BFavoritos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BFavoritos.setText("Ver favoritos");
        BFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFavoritosActionPerformed(evt);
            }
        });
        getContentPane().add(BFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 215, 110, 30));

        BGenerarPdf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BGenerarPdf.setText("PDF");
        BGenerarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGenerarPdfActionPerformed(evt);
            }
        });
        getContentPane().add(BGenerarPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 110, 40));

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derActionPerformed
        // TODO add your handling code here:
        contador_bd++;
        contador_poke++;

        if (contador_bd<508){
            dibujaElPokemonQueEstaEnLaPosicion(contador_poke);
            nombrePokemon.setText(this.pokemon.consulta_pokemon(""+contador_bd));
            pokemon.consulta_nombtepk(this.pokemon.consulta_pokemon(""+contador_bd));
            pokemon.desplegar_datospk(nombre, alto, ancho, especies, color, habitat, experiencia);
        }
    }//GEN-LAST:event_derActionPerformed

    private void izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izqActionPerformed
        // TODO add your handling code here:
        //evento cuando el usr de click en izquierdo
        contador_bd--;
        contador_poke--;
        if(contador_bd >=1 && contador_poke>=0){
            dibujaElPokemonQueEstaEnLaPosicion(contador_poke);
            nombrePokemon.setText(this.pokemon.consulta_pokemon(""+contador_bd));
            pokemon.consulta_nombtepk(this.pokemon.consulta_pokemon(""+contador_bd));
            pokemon.desplegar_datospk(nombre, alto, ancho, especies, color, habitat, experiencia);
           
        } 
    }//GEN-LAST:event_izqActionPerformed

    private void AgregarmenosFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarmenosFavActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps= null;
     
        try
        {
            ConexionDB con= new ConexionDB();
            Connection conn = con.conexion();
            ps= conn.prepareStatement("insert into tb_menosfavoritos(usuario, pokemon)values('"+nombreusuario.getText()+"','"+nombrePokemon.getText()+"')");
            
            ps.execute();
            JOptionPane.showMessageDialog(null, "Agregado a menos favoritos");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al guardar");
            System.out.println(ex);
        }  
    }//GEN-LAST:event_AgregarmenosFavActionPerformed

    private void AgregarFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFavActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps= null;
     
        try
        {
            ConexionDB con= new ConexionDB();
            Connection conn = con.conexion();
            ps= conn.prepareStatement("insert into tb_favoritos(usuario, pokemon)values('"+nombreusuario.getText()+"','"+nombrePokemon.getText()+"')");
//            ps.setString(1, nombreusuario.getText());
//            ps.setString(2, nombrePokemon.getText());
//            cuerito.setText(ps.toString());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Agregado a favoritos");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al guardar");
            System.out.println(ex);
        }  
    }//GEN-LAST:event_AgregarFavActionPerformed

    private void BGenerarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGenerarPdfActionPerformed
        // TODO add your handling code here:
       Connection conexion=null;
        try 
        {
        conexion=ConexionDB.conexion();
        JasperReport reporte = null;
        String path="C:\\Users\\13237\\OneDrive\\Desktop\\pokedexp1A\\pokedexp1A\\src\\main\\java\\GenerarReporte\\reporte.jasper";
        reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
        JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conexion);
        
        JasperViewer view = new JasperViewer(jprint, false);
        view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        view.setVisible(true);
        
        } catch (JRException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_BGenerarPdfActionPerformed

    private void BFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFavoritosActionPerformed
        //abrir el sistema
        Favoritos form=new Favoritos();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BFavoritosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarFav;
    private javax.swing.JButton AgregarmenosFav;
    private javax.swing.JButton BFavoritos;
    private javax.swing.JButton BGenerarPdf;
    private javax.swing.JLabel alto;
    private javax.swing.JLabel ancho;
    private javax.swing.JLabel color;
    private javax.swing.JButton der;
    private javax.swing.JLabel especies;
    private javax.swing.JLabel experiencia;
    private javax.swing.JLabel habitat;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton izq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombrePokemon;
    public static javax.swing.JTextField nombreusuario;
    // End of variables declaration//GEN-END:variables

}
